baseURL = 'https://taosky.org'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
theme = 'farallon'

title = "Taosky 的博客"
contentDir = 'content'

[menu]
  [[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 4

  [[menu.main]]
  name = "文章"
  url = "/"
  weight = 1

[taxonomies]
  category = 'categories'
  tag = 'tags'

[Params]
  # 基础设置
  description = '个人博客，用于分享'
  mainSections = ['story','memo']
  showAuthor = false
  authorName = 'Taosky'
  authorDescription = ''
  ## 自行替换主题目录assets/layouts/下的logo.jpeg
  authorAvatar = '/images/logo.jpeg' 
  customCSS=true
  # 文章内目录
  toc = true

  # 谷歌Adsense, 按要求自行放置ads.txt
  googleAd = 'ca-pub-00000000000000'
  
  # 底部社交链接
  footer_sns = true
  feed = '/index.xml'
  # twitter = 'https://twitter.com/Taosky'
  instagram = 'https://www.instagram.com/taoskycn/'
  github = 'https://github.com/Taosky'
  # telegram = 'https://t.me/s/Taosky'

  # 文章点赞和浏览统计
  post_like = true
  post_view = true

  # 不要修改
  actionDomain = 'https://v.wpista.com/'

  # Giscus评论
  giscusRepo = 'XXX/XXXX'
  giscusRepoId = 'XXXXXXXXXXXXXXXXXX'
  giscusCategory = 'Announcements'
  giscusCategoryId = 'DIC_xxxxxxxxx'

[outputs]
  home = [ "HTML","RSS","JSON"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.highlight]
  style = 'dracula'  # https://swapoff.org/chroma/playground
