baseURL = 'https://taosky.org'
languageCode = 'zh-cn'
timezone = 'Asia/Shanghai'
theme = 'farallon'

title = "Taosky 的博客"
contentDir = 'content'

[menu]
  [[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 4

  [[menu.main]]
  name = "看过"
  url = "/watch/"
  weight = 3

  [[menu.main]]
  name = "文章"
  url = "/"
  weight = 1


[taxonomies]
  category = 'categories'
  tag = 'tags'

[Params]
  search= true
  description = '个人博客'
  toc = true
  mainSections = ['story','memo']
  indexName = 'taosky'
  showAuthor = false
  authorName = 'Taosky'
  authorDescription = ''
  authorAvatar = '/images/logo.jpeg'
  customCSS=true
  # googleAd='ca-pub-xxxxxxxxxxxxxxxx'
  post_like = true
  post_view = true
  actionDomain = 'https://v.wpista.com/'
  giscusRepo = 'Taosky/taosky.github.io'
  giscusRepoId = 'xxxxxxxxxxxxxxxxx='
  giscusCategory = 'Announcements'
  giscusCategoryId = 'DIC_xxxxxxxxxx'

[outputs]
  home = [ "HTML","RSS","JSON"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[markup.highlight]
  style = 'dracula' # https://swapoff.org/chroma/playground